### PR TITLE
Bugfixes: assignment errors and regex update

### PR DESCRIPTION
**Pull request by david-abell**
I found some not so great assignment errors while updating the regex matches to handle tags like `'data-background-image-set'` with quote `url('...')` sources.

This pull request fixes those bugs and updates the regex matching.

This pull request also fixes a crash when a user config file is not present. I changed to much with the prior version and somehow broke that too. Oops. Hopefully there is not more to come.

There is still one bug with this build and the prior build related to regex match and replace of said urls. They work as expected when the sources are found at compile time but if the sources cannot be found:

This compiles correctly to local image:
```
<div data-background-image-set="url('./images/gallery/kitchens/thumbs/kitch009-thumb.jpg') 1x"
```

This throws a compile error: 
```
<div data-background-image-set="url('./images/gallery/kitchens/thumbs/kitch009-thumb.jpg') 1x"
```

The error should like like:
```
@parcel/core: Failed to resolve './images/gallery/kitchens/kitch001.jp' from './src/portfolio.html'
@parcel/resolver-default: Cannot load file './images/gallery/kitchens/kitch001.jp' in './src'.
```
Instead it throws this error...
```
Error: dependency.specifier.match is not a function
TypeError: dependency.specifier.match is not a function
  at ResolverRunner.resolve (\node_modules\@parcel\core\lib\requests\PathRequest.js:179:38)
  at async Object.run (\node_modules\@parcel\core\lib\requests\PathRequest.js:104:16)
  at async RequestTracker.runRequest (\node_modules\@parcel\core\lib\RequestTracker.js:721:20)
  at async AssetGraphBuilder.runPathRequest (\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:762:18)
  at async PromiseQueue._runFn (\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
  at async PromiseQueue._next (\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)
```

Maybe a second set of eyes can sort that bug out. If not, I can ask the parcel team.

### CODE REVIEW

**Comment by moritzlaube** [comment]
Hm. Cant't find a immediate reason. But will look more into it. Thanks for your great input on this!

**Comment by mischnic** [comment]
Aren't the two snippets you posted as "This compiles correctly" and "This throws" the same?

> dependency.specifier.match is not a function

That probably happened because the transformer called `asset.addURLDependency` not with a string but some other object. And Parcel doesn't explicitly validate everything coming from plugins


Yeah, `dependency.specifier` in that case is
```
[
	'./images/gallery/kitchens/thumbs/kitch009-thumb.jpg',
	index: 5,
	input: "url('./images/gallery/kitchens/thumbs/kitch009-thumb.jpg') 1x",
	groups: undefined
]
```

**Comment by mischnic** [comment]
This is probably the fix:
```diff
diff --git index.js index.js
index 3936852..202a6c8 100644
--- index.js
+++ index.js
@@ -104,12 +104,12 @@ module.exports = new Transformer({
           .split(',')
           .map(el => {
             if (regexQuoteInsideParen.test(el)) {
-              const url = el.match(regexQuoteInsideParen)
+              const url = el.match(regexQuoteInsideParen)[0]
               const updatedUrl = asset.addURLDependency(url, {})
               return el.replace(regexQuoteInsideParen, updatedUrl)
             }
             if (regexInsideParen.test(el)) {
-              const url = el.match(regexInsideParen)
+              const url = el.match(regexInsideParen)[0]
               const updatedUrl = asset.addURLDependency(url, {})
               return el.replace(regexInsideParen, updatedUrl)
             }
```
because match doesn't return the matched string but instead the object above.

**Comment by moritzlaube** [comment]
Thanks @mischnic, that seemed to do the trick. I also fixed a bug with wrongly formatted whitespace. Tests are working now. @david-abell: Do you wanna check on your side as well? Thanks for all of you guys' effort!

**Comment by david-abell** [comment]
Nice simple fix! And I know I logged `const url` to check that line too but it just outputs the expected string unless you also do a typeof check. That shows the sneaky object. 

I've confirmed parcel gives the correct errors now. Works great

**Pull request merged**
